# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HAminiEMS
version: "1.0.0"
slug: haminiems
description: Mini Energy Management System f√ºr Home Assistant
url: "https://github.com/GuidoJeuken-6512/HAminiEMS"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  ha_url: "http://supervisor/core"
  ha_token: ""
  refresh_interval: 30
schema:
  ha_url: "str?"
  ha_token: "str?"
  refresh_interval: "int(1,)?"
image: "ghcr.io/guidojeuken-6512/{arch}-addon-haminiems"

